# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  gmail_username: kristincorona@gmail.com
  gmail_password: Mawad7fu
  secret_key_base: 8ee645cbee0fd93bc599f665668831ea2f5d4817d8b7e6822fec676cfc67837324d1ca140ca1d4aec530fdbd3ba1897910b8987bbb18ea88845b229c021eb378

test:
  secret_key_base: 218f89c4d2a7b4d1dd7fc0f66ca46323fa5fbc1ce5e0eb93b5d57d98ffbf87a117202940fe84ba8282a002d7e410030d999fcb4500ac6bff6b632162de0b1e79

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  gmail_username: <%= ENV["kristincorona@gmail.com"] %>
  gmail_password: <%= ENV["Mawad7fu"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
